---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  vars:
    iim_agent_version: 1.10.1000.20241118_1329
    iim_install_path: /opt/IBM/InstallationManager
    websphere_version: 9.0.5.22
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}

  roles:
    - iim
    - websphere
