---
- name: Create temporary directory
  file:
    path: /tmp/iim/
    recurse: yes
    mode: 0755
    state: directory
  # register: tmp_dir

- name: Copy installer
  copy:
    src: "{{ iim_installer_path }}"
    dest: /tmp/iim/iimInstaller.zip
  when: download_url is not defined
  # register: iim_zip

- name: Download installer
  get_url:
    url: "{{ download_url }}/{{ iim_installer_path }}"
    dest: /tmp/iim/iimInstaller.zip
    headers: "{{ download_header }}"
  when: download_url is defined
  # register: iim_zip

- name: Extract IIM installer
  unarchive:
    # src: "{{ iim_zip.dest }}"
    src: /tmp/iim/iimInstaller.zip
    dest: /tmp/iim/
    remote_src: yes
    mode: 0755
    creates: /tmp/iim/installc

- name: Run IIM installer
  command:
    cmd: ./installc -acceptLicense -iD {{ iim_install_path }}
    chdir: /tmp/iim/
    creates: "{{ iim_install_path }}"
  become: yes

- name: Delete temporary directory
  file:
    path: /tmp/iim/
    state: absent
  become: yes
