---
- name: Create temporary directory
  win_file:
    path: C:\Temp\IIMInstall
    state: directory
  register: tmp_dir

# - name: Download IIM installer
#   win_get_url:
#     dest: "{{ tmp_dir.path }}/agent.installer.win32.win32.x86_64_{{ iim_agent_version }}.zip"
#     url: "{{ artifactory_url }}/{{ artifactory_repo }}/SoftwareInstallers/IIM/agent.installer.win32.win32.x86_64_{{ iim_agent_version }}.zip"
#     headers:
#       X-JFrog-Art-Api: "{{ artifactory_token }}"
#   register: iim_zip

- name: Extract IIM installer
  win_unzip:
    src: "{{ iim_zip.dest }}"
    dest: "{{ tmp_dir.path }}"
    remote_src: yes
    creates: "{{ tmp_dir.path }}/installc.exe"

- name: Run IIM installer
  win_command: installc.exe -acceptLicense -iD {{ iim_install_path }}
  args:
    chdir: "{{ tmp_dir.path }}"

- name: Delete temporary directory
  win_file:
    path: "{{ tmp_dir.path }}"
    state: absent
