---
- name: Create temporary directory
  win_file:
    path: C:\Temp\iim
    state: directory
  register: tmp_dir


- name: Copy installer
  copy:
    src: "{{ iim_installer_path }}"
    dest: "{{tmp_dir.path}}/iim_installer.tar.gz"
  register: iim_zip

- name: Extract IIM installer
  win_unzip:
    src: "{{ iim_zip.dest }}"
    dest: "{{ tmp_dir.path }}"
    remote_src: yes
    creates: "{{ tmp_dir.path }}/installc.exe"

- name: Run IIM installer
  win_command: installc.exe -acceptLicense -iD {{ iim_install_path }}
  args:
    chdir: "{{ tmp_dir.path }}"

- name: Delete temporary directory
  win_file:
    path: "{{ tmp_dir.path }}"
    state: absent
