---
liberty_fp_path: WLP/21.0.0.9-WS-LIBERTY-ND-FP.zip
liberty_installers_path: WLP/was.repo.16002.liberty.nd.zip
liberty_pid: 21.0.9.20210824_2342

liberty_java_zip_path: Java/IBM/ibm-java-sdk-8.0-6.35-linux-x64-installmgr.zip
liberty_java_pid: com.ibm.java.jdk.v8_8.0.6035.20210716_0654
