---
liberty_fp_path: WLP/24.0.0.12-WS-LIBERTY-ND-FP.zip
liberty_installers_path: WLP/was.repo.16002.liberty.nd.zip
liberty_pid: 24.0.12.20241119_0657
jdk_version: 21.0
jdk_installation_way: unzip
liberty_java_zip_path: Java/IBM/ibm-semeru-open-jdk_x64_linux_21.0.5_11_openj9-0.48.0.tar.gz
