---
- name: Create zip directory
  file:
    path: {{ temp_dir }}
    state: directory

- name: Copy WAS repo
  copy:
    src: "{{ websphere_fp_path }}/{{ item }}"
    dest: "{{ temp_dir }}/{{ item }}"
  loop: "{{ websphere_fp_archive_list }}"
  when: download_url is not defined

- name: Download repo
  get_url:
    dest: "{{ temp_dir }}/{{ item }}"
    url: "{{ download_url }}/{{ websphere_fp_path }}/{{ item }}"
    headers: "{{ download_header }}"
  loop: "{{ websphere_fp_archive_list }}"
  when: download_url is defined

- name: Create repo directories
  file:
    path: /tmp/repo
    state: directory

- name: Extract installers
  unarchive:
    src: "{{ temp_dir }}/{{ item }}"
    dest: /tmp/repo
    remote_src: yes
  loop: "{{ websphere_fp_archive_list }}"

- name: Install package
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "com.ibm.websphere.ND.{{ websphere_pid }}"
    path: "{{ websphere_install_path }}"
    repo: /tmp/repo
    state: present

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/repo
    - "{{ temp_dir }}"
