---
- name: Include version variables
  include_vars: "v{{ websphere_version }}.yml"

- name: Check packages
  iim_info:
    iim_path: "{{ iim_install_path }}"
    product_id: "com.ibm.websphere.ND.{{ websphere_pid }}"
  register: iim_info

- name: Install Base version
  include_tasks: "{{ websphere_pid.split('_') | first }}_base_install.yml"
  when: not iim_info.base_installed

- name: Install Fixpack version
  include_tasks: fixpack_install.yml
  when: not iim_info.exact_installed

- name: Setup environment variables
  include_tasks: env.yml

- name: Configure WebSphere
  include_tasks: configure.yml

- name: Ensure /opt/Props dir exists
  file:
    path: /opt/Props
    state: directory

- name: Copy AppServer.properties
  template:
    dest: /opt/Props/AppServer.properties
    src: AppServer.properties.j2
    mode: 0755
    force: no

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/repo
    - /tmp/repo-zips
