---
- name: Create zip directory
  file:
    path: {{ temp_dir }}
    state: directory

- name: Copy WAS repo
  copy:
    src: "{{ websphere_base_path }}/{{ item }}"
    dest: "{{ temp_dir }}/{{ item }}"
  loop: "{{ websphere_base_archive_list }}"
  when: download_url is not defined

- name: Download WAS repo
  get_url:
    dest: "{{ temp_dir }}/{{ item }}"
    url: "{{ download_url }}/{{ websphere_base_path }}/{{ item }}"
    headers: "{{ download_header }}"
  loop: "{{ websphere_base_archive_list }}"
  when: download_url is defined

- name: Create WAS repo directory
  file:
    path: "/tmp/repo"
    state: directory

- name: Extract WAS installers
  unarchive:
    src: "{{ temp_dir }}/{{ item }}"
    dest: /tmp/repo
    remote_src: yes
    creates: "/tmp/repo/disk{{ (index + 1) | string }}"
  loop: "{{ websphere_base_archive_list }}"
  loop_control:
    index_var: index

- name: Install WAS
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "{{ websphere_base_pid }}"
    path: "{{ websphere_install_path }}"
    repo: /tmp/repo
    state: present
  when: "iim_info.packages | select('match', 'com.ibm.websphere.ND.*') | list | length == 0"

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/repo
    - {{ temp_dir }}
