---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  vars:
    liberty_version: "24.0.0.9-JDK17"
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}

  roles:
    - iim
    - liberty
