---
- name: Converge
  hosts: all

  collections:
    - ibm.spm_middleware

  vars:
    websphere_version: 8.5.5.17
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}

  roles:
    - iim
    - websphere
