---
base_install_file: 'fmw_14.1.1.0.0_wls.jar'
weblogic_version: 14.1
opatch: 'p28186730_1394214_Generic.zip'
opatch_version: 13.9.4.2.14
patch: 'p36124787_141100_Generic.zip'
patch_number: 36124787
napply: false
patch_folder: '36124787'
java_archive_file: jdk-8u401-linux-x64.tar.gz
java_version_path: 'jdk1.8.0_401'
