---
- name: Converge
  hosts: all

  collections:
    - wh_spm.middleware

  vars:
    artifactory_url: "https://{{ lookup('env', 'JFROG_GEO') | default('eu', true) }}.artifactory.swg-devops.com/artifactory"

  roles:
    - db2
