---
driver:
  name: docker
  provider:
    name: docker

# lint: |
#   set -e
#   yamllint .

platforms:
  # - name: centos-7
  #   image: centos:7
  #   dockerfile: ../_resources/Dockerfile.j2
  #   pre_build_image: False
  #   privileged: True
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  #   command: "/usr/lib/systemd/systemd"
  #   environment:
  #     container: docker
  - name: centos-8
    image: centos:8
    dockerfile: ../_resources/Dockerfile.j2
    pre_build_image: false
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/lib/systemd/systemd"
    environment:
      container: docker

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stderr_callback: debug
      stdout_callback: debug
  env:
    ANSIBLE_FORCE_COLOR: 'true'
