---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  pre_tasks:
    - name: Install sudo and PAM dependencies
      yum:
        name:
          - sudo
          - pam
          - shadow-utils
        state: present
    - name: Fix PAM configuration for sudo
      lineinfile:
        path: /etc/pam.d/sudo
        line: "auth sufficient pam_unix.so"
        state: present

  roles:
    - db2

  vars:
    db2_version: "11.5.8.0"
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}
