---
db2_install_path: /opt/IBM/db2
db2_version: 11.1.4.6
db2_product: DB2_SERVER_EDITION
db2_bypass_prereq_check: False
db2_activate: True
db2_installer_path: /tmp/db2_installer.tar.gz
db2_license_path: /tmp/db2ese_u.lic

db2_db_create: True
db2_db_name: DATABASE
db2_db_username: "{{ lookup('env', 'DB2_USER') }}"
db2_db_password: "{{ lookup('env', 'DB2_PASSWPRD') }}"
db2_db_spm_enc: "{{ lookup('env', 'DB2_ENC_PASSWORD') }}"
db2_db_drop_required: False

bootstrap_dateformat: 'dd MM yyyy'
bootstrap_dateseparator: '/'
bootstrap_dmx_locale: 'en_US'

# Artifactory config
artifactory_token: "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"
artifactory_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}"
artifactory_repo: "{{ lookup('env', 'ARTIFACTORY_REPO') }}"

# Common
profiled_path: /opt/profile.d
