---

liberty_install_path: /opt/IBM/WebSphere/Liberty
jdk_install_path: /opt/IBM/WebSphere/Liberty/java/17

liberty_version: 23.0.0.12

# Default JVM Options
liberty_default_heapsize: 1024m
liberty_enable_verbose_gc: false
liberty_extra_jvm_options: []
security_username: websphere
# use encrypted password
security_password: dummypassword

# Common
profiled_path: /opt/profile.d
# Server info for downloading installers / repos directly, leave blank to copy
# download_url:   # e.g. https://artifactory/repo
# download_header:  # e.g. X-JFrog-Art-Api: "{{ lookup('env', 'MYTOKEN') }}"
