---
- name: Copy license
  copy:
    src: "{{ db2_license_path }}"
    dest: /tmp/db2server.lic
  register: target_lic_file

- name: Apply license
  command: "{{ db2_install_path }}/adm/db2licm -a {{ target_lic_file.dest }}"

- name: Cleanup
  file:
    path: "{{ target_lic_file.dest }}"
    state: absent
