---
- name: Converge
  hosts: all

  collections:
    - ibm.spm_middleware

  roles:
    - db2

  vars:
    db2_version: "11.5.5.0"
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}
