---
name: Molecule Tests

# Only execute molecule tests when running within the IBM org
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  molecule:
    if: github.repository_owner == 'IBM'
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - websphere-v90-centos-8
          - websphere-v85-centos-7
          - db2111
          - db2115
          - oracle12cR1-centos-7
          - oracle12cR2-centos-7
          - oracle19c-centos-8
          - iim-191-centos-8
          - ihs-v90-centos-8
          - ihs-v80-centos-7
          - liberty-centos-7
          - liberty-centos-8
          - weblogic-centos-7
          - weblogic-centos-8
    runs-on: ubuntu-latest
    env:
      python_ver: 3.8
      collection_namespace: ibm
      collection_name: spm_middleware

    defaults:
      run:
        working-directory: ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }}

    steps:
      - name: Checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }}

      - name: Setup Python v${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: Setup Python Cache
        uses: actions/cache@v2
        with:
          key: pip-${{ matrix.scenario }}-${{ hashFiles('ci-requirements.txt') }}
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r ci-requirements.txt

      - name: Prepare environment
        run: |
          mkdir -pv ~/.ansible/collections/${{ env.collection_namespace }}
          ln -s ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }} ~/.ansible/collections/${{ env.collection_namespace }}/${{ env.collection_name }}
          chmod -v +x ./scripts/*

      - name: Run Molecule test
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          ARTIFACTORY_TOKEN: "${{ secrets.ARTIFACTORY_TOKEN }}"
          ARTIFACTORY_REPO: "${{ secrets.ARTIFACTORY_REPO }}"
          ARTIFACTORY_URL: "${{ secrets.ARTIFACTORY_URL }}"
