---
name: Molecule Tests

# Run this workflow on push events, PRs to main branch, and manual dispatch events
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  molecule:
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - db2-111-centos-7
          - db2-115-centos-8
          - iim-191-centos-8
    runs-on: ubuntu-latest
    env:
      python_ver: 3.8
      collection_namespace: ibm
      collection_name: spm_middleware

    defaults:
      run:
        working-directory: ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }}

    steps:
      - name: Checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }}

      - name: Setup Python v${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: Setup Python Cache
        uses: actions/cache@v2
        with:
          key: pip-${{ matrix.scenario }}-${{ hashFiles('ci-requirements.txt') }}
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r ci-requirements.txt

      - name: Prepare environment
        run: |
          mkdir -pv ~/.ansible/collections/${{ env.collection_namespace }}
          ln -s ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }} ~/.ansible/collections/${{ env.collection_namespace }}/${{ env.collection_name }}
          chmod -v +x ./scripts/*

      - name: Download installers
        run: |
          true
        # Uncomment when credentials are available
        # run: |
        #   ./scripts/downloadInstaller.sh ${{ matrix.scenario }}

      - name: Run Molecule test
        run: |
          molecule list
        # Uncomment when credentials are available
        # run: |
        #   molecule test -s ${{ matrix.scenario }}
