---
name: Test Collection

# Run this workflow on push events, PRs to main branch, and manual dispatch events
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - db2-111-centos-7
          - db2-115-centos-8
          - iim-191-centos-8
    runs-on: ubuntu-latest
    env:
      python_ver: 3.8
      collection_namespace: ibm
      collection_name: spm_middleware

    steps:
      - name: Checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/${{ env.collection_namespace }}/${{ env.collection_name }}

      - name: Setup Python v${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: Setup Python Cache
        uses: actions/cache@v2
        with:
          key: pip-${{ matrix.scenario }}-${{ hashFiles('ci-requirements.txt') }}
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r ci-requirements.txt
          curl -sLO https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64
          sudo install yq_linux_amd64 /usr/local/bin/yq

      - name: Prepare environment
        run: |
          pwd
          mkdir -pv ~/.ansible/collections/${{ env.collection_namespace }}
          # ln -s ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME ~/.ansible/collections/${{ env.collection_namespace }}/${{ env.collection_name }}
          chmod -v +x ./scripts/*

      - name: Check environment
        run: |
          pwd
          ls
          echo "Scenario: ${{ matrix.scenario }}"
          env | sort
